### PR TITLE
Meeting notes 2020-08-24

### PR DESCRIPTION
**Pull request by JT-os**
Signed-off-by: JT Nelson <64504001+JT-os@users.noreply.github.com>

### CODE REVIEW

**Comment by JT-os** [comment]
I attempted to manually set the "Signed-off-by: <email>" in the comments without doing it from a local repo and only using the  web UI Github to Github. This is supposedly an optional way to --signoff according to a couple resources I found.  The DCO bot did error.  I then changed the comment based signoff email and format according to the DCO error message and it appears to still fail.

Let me know if you have a way to kick this in.  If not, I'll make a local repo and do it the long way.  I was hoping a Github > Github workflow would work since I'll be onboarding some inexperienced devs that will only be using Github web repos and not local ones.  Sorry about the extra email noise in experimenting on this.

**Comment by AWhetter** [comment]
I don't know if you can do it with the web UI. But the format of the signoff looks incorrect. The format of your first commit looks correct but didn't match the committer (at least that's what the details page of the failure says). I think it should be

```
Signed-off-by: JT Nelson <64504001+JT-os@users.noreply.github.com>
```

**Comment by JT-os** [comment]
Right.  I did a message edit on this end with that format and it kicked it back out still after reevaluating.  I probably need to change on my fork end and let it propagate forward.  I'll fire up my test repo and work this out to keep the noise down here.  Then I'll go from there if that's okay with you.  I need to know what works with the Web UI and not via experimentation for new university Py programmers targeted for D&I onboarding that work from the cloud with a tablet and don't use local storage.   I'll make sure and wrap this up in the next hour or two.  Thanks for helping out.

**Comment by AWhetter** [comment]
No worries

**Comment by JT-os** [comment]
Closing to retry with a second PR and manually inserted Signed-of-by solely from the Github Web UI.

**Pull request closed without merging**
